# This Docker file creates an image to run Flask Demonstration App of lip-reading

From python:3.9.13

RUN pip install --upgrade pip

# Set the working directory in the container
WORKDIR /ml-ops-A2

ADD . /ml-ops-A2

# Install the Python dependencies
RUN pip install -r requirements.txt


# Setting the entry point command to run the flask application
CMD ["python","main.py"]